# Render service definition for free web service
# Render service definition for free web service
services:
  - type: web
    name: carpet-designer
    env: python
    region: oregon # or your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production